# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Windowbuttom.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Windowbuttom(object):
    def setupUi(self, Windowbuttom):
        Windowbuttom.setObjectName("Windowbuttom")
        Windowbuttom.resize(665, 421)
        self.centralwidget = QtWidgets.QWidget(Windowbuttom)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 130, 181, 101))
        self.pushButton.setObjectName("pushButton")
        Windowbuttom.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Windowbuttom)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 26))
        self.menubar.setObjectName("menubar")
        self.menuEncriptar = QtWidgets.QMenu(self.menubar)
        self.menuEncriptar.setObjectName("menuEncriptar")
        self.menuDesencriptar = QtWidgets.QMenu(self.menubar)
        self.menuDesencriptar.setObjectName("menuDesencriptar")
        self.menuOpciones = QtWidgets.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        Windowbuttom.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Windowbuttom)
        self.statusbar.setObjectName("statusbar")
        Windowbuttom.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuEncriptar.menuAction())
        self.menubar.addAction(self.menuDesencriptar.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(Windowbuttom)
        QtCore.QMetaObject.connectSlotsByName(Windowbuttom)

    def retranslateUi(self, Windowbuttom):
        _translate = QtCore.QCoreApplication.translate
        Windowbuttom.setWindowTitle(_translate("Windowbuttom", "MainWindow"))
        self.pushButton.setText(_translate("Windowbuttom", "Encriptar"))
        self.menuEncriptar.setTitle(_translate("Windowbuttom", "Encriptar"))
        self.menuDesencriptar.setTitle(_translate("Windowbuttom", "Desencriptar"))
        self.menuOpciones.setTitle(_translate("Windowbuttom", "Opciones"))
        self.menuAyuda.setTitle(_translate("Windowbuttom", "Ayuda"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Windowbuttom = QtWidgets.QMainWindow()
    ui = Ui_Windowbuttom()
    ui.setupUi(Windowbuttom)
    Windowbuttom.show()
    sys.exit(app.exec_())
